"use client";

import{useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
type Bill={table_number:number;table_label:string;session_id:string|null;status:string;items:{id:string;name:string;quantity:number;unit_price_amount:number;total_amount:number}[];total_amount:number;paid_amount:number};

export default function CustomerBill({token}:{token:string}){const[bill,setBill]=useState<Bill|null>(null);const[loading,setLoading]=useState(true);const[showPay,setShowPay]=useState(false);const[method,setMethod]=useState("MPESA");const[phone,setPhone]=useState("");const[paying,setPaying]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
  async function load(){const{data}=await createClient().rpc("customer_table_bill",{p_qr_token:token});setBill(data as Bill|null);setLoading(false)}
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[token]);
  async function pay(amount:number){setPaying(true);setError("");const res=await fetch("/api/customer/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({qrToken:token,amount,method,phone,requestId:crypto.randomUUID()})});const out=await res.json();setPaying(false);if(!res.ok){setError(out.error);return}setSuccess(`Payment received from ${out.maskedPhone}. Reference ${out.reference}`);setShowPay(false);await load()}
  if(loading)return <main className="customer-phone"><div className="customer-loading">Checking this table securely…</div></main>;
  if(!bill)return <main className="customer-phone"><div className="customer-empty"><div>⌁</div><h1>QR not recognised</h1><p>Please scan the QR label fixed to your table again.</p></div></main>;
  if(!bill.session_id)return <main className="customer-phone"><div className="customer-top"><b>UZUNGUNI</b><span>{bill.table_label}</span></div><div className="customer-empty"><div>✓</div><h1>No active bill</h1><p>Your table is ready. Ask your waiter to initiate the table after taking your order.</p></div></main>;
  const remaining=Math.max(0,bill.total_amount-bill.paid_amount);
  return <main className="customer-phone"><div className="customer-top"><b>UZUNGUNI</b><span>{bill.table_label}</span></div><section className="customer-content"><p className="eyebrow">SECURE LIVE BILL</p><h1>Your bill</h1><p className="muted">Review the items entered by your waiter before paying.</p><div className="verified-line"><span>● Live session</span><b>{bill.status.replaceAll("_"," ")}</b></div><div className="customer-items">{bill.items.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.quantity} × TZS {item.unit_price_amount.toLocaleString()}</small></span><strong>TZS {item.total_amount.toLocaleString()}</strong></div>)}</div><div className="customer-totals"><span><i>Total bill</i><b>TZS {bill.total_amount.toLocaleString()}</b></span><span><i>Paid</i><b>TZS {bill.paid_amount.toLocaleString()}</b></span><span className="customer-remaining"><i>Remaining</i><strong>TZS {remaining.toLocaleString()}</strong></span></div>
    {success&&<div className="paid-banner">✓ {success}</div>}
    {remaining>0&&!showPay&&<button className="primary" onClick={()=>setShowPay(true)}>Pay TZS {remaining.toLocaleString()}</button>}
    {remaining>0&&showPay&&<div className="pay-panel"><p className="eyebrow">CHOOSE WALLET</p><div className="wallet-choice">{[["MPESA","M-Pesa"],["SELCOM_PESA","Selcom Pesa"],["AZAMPESA","AzamPesa"]].map(([id,label])=><button key={id} onClick={()=>setMethod(id)} className={method===id?"selected":""}>{label}</button>)}</div><label>Wallet phone number<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="0712 345 678"/></label><p className="secure-payment">🔒 Uzunguni never asks for your mobile-money PIN.</p>{error&&<p className="form-error">⚠ {error}</p>}<button className="primary" onClick={()=>pay(remaining)} disabled={paying}>{paying?"Confirming securely…":`Send TEST payment · TZS ${remaining.toLocaleString()}`}</button><button className="cancel-pay" onClick={()=>setShowPay(false)} disabled={paying}>Cancel</button></div>}
    {remaining===0&&!success&&<div className="paid-banner">✓ Payment received · Server verified</div>}<p className="demo-note">TEST MODE · Server-confirmed simulation · No real money collected</p></section></main>}
