"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Item = { id: string; item_name: string; unit_price_amount: number; quantity: number };
type Menu = { id: string; name: string; category: string; price_amount: number };

export default function TableWorkspace({ sessionId, sessionStatus, items, menu, payments, isAdmin, accessEnabled, accessExpiresAt }: { sessionId: string; sessionStatus:string; items: Item[]; menu: Menu[]; payments: {id:string;amount:number;payment_method:string;status:string;provider_reference:string|null;created_at:string}[]; isAdmin: boolean; accessEnabled:boolean; accessExpiresAt:string|null }) {
  const router = useRouter(); const [menuId, setMenuId] = useState(""); const [quantity,setQuantity]=useState(1); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const total = items.reduce((n,i) => n + i.unit_price_amount * i.quantity, 0); const paid = payments.filter(p => p.status === "PAID").reduce((n,p) => n + p.amount, 0); const remaining = Math.max(0,total-paid);
  async function addItem() { setBusy(true); setError(""); const res = await fetch("/api/order-items", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({sessionId,menuItemId:menuId,quantity}) }); const out=await res.json(); setBusy(false); if(!res.ok){setError(out.error);return;} setMenuId(""); setQuantity(1); router.refresh(); }
  async function changeQuantity(itemId:string,next:number){if(next<1||next>999)return;setBusy(true);setError("");const res=await fetch("/api/order-items",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId,quantity:next})});const out=await res.json();setBusy(false);if(!res.ok){setError(out.error);return;}router.refresh()}
  async function simulate() { const raw=prompt(`Demo only: amount to confirm (remaining TZS ${remaining.toLocaleString()})`,String(remaining)); if(!raw)return; const amount=Number(raw.replaceAll(",","")); const res=await fetch("/api/admin/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,amount})}); const out=await res.json(); if(!res.ok){setError(out.error);return;} router.refresh(); }
  async function setCustomerAccess(enabled:boolean){setBusy(true);setError("");const res=await fetch("/api/tables/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,enabled,durationMinutes:30})});const out=await res.json();setBusy(false);if(!res.ok){setError(out.error);return}router.refresh()}
  async function closeTable(){if(!confirm("Close this table? Its customer access will be revoked and the table will become available for a new session."))return;setBusy(true);setError("");const res=await fetch("/api/tables/close",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId})});const out=await res.json();setBusy(false);if(!res.ok){setError(out.error);return}router.push(isAdmin?"/admin":"/waiter");router.refresh()}
  return <div className="workspace-stack">
    <section className="content-card"><div className="card-heading"><div><p className="eyebrow">CUSTOMER QR ACCESS</p><h2>{accessEnabled?"Scanning is temporarily open":"Bill is private"}</h2></div><span className={`status-chip ${accessEnabled?"paid":"neutral"}`}>{accessEnabled?"● ACCESS OPEN":"● LOCKED"}</span></div><p className="muted">{accessEnabled?`New scans are allowed until ${accessExpiresAt?new Date(accessExpiresAt).toLocaleTimeString():"the access window expires"}.` : "The permanent QR reveals no bill until you open a short access window."}</p>{accessEnabled?<button className="outline-button" onClick={()=>setCustomerAccess(false)} disabled={busy}>Lock customer access now</button>:<button className="staff-button" onClick={()=>setCustomerAccess(true)} disabled={busy||!items.length}>Open QR access for 30 minutes</button>}</section>
    <section className="content-card"><div className="card-heading"><div><p className="eyebrow">ORDER</p><h2>Items ordered</h2></div><span>{items.reduce((n,i)=>n+i.quantity,0)} items</span></div>
      <div className="order-list">{items.map(item=><div key={item.id}><span><b>{item.item_name}</b><small>TZS {item.unit_price_amount.toLocaleString()} each</small></span><div className="order-qty"><button aria-label={`Reduce ${item.item_name}`} onClick={()=>changeQuantity(item.id,item.quantity-1)} disabled={busy||item.quantity<=1}>−</button><b>{item.quantity}</b><button aria-label={`Increase ${item.item_name}`} onClick={()=>changeQuantity(item.id,item.quantity+1)} disabled={busy}>+</button></div><strong>TZS {(item.quantity*item.unit_price_amount).toLocaleString()}</strong></div>)}{!items.length&&<div className="empty-inline">No items added yet.</div>}</div>
      <div className="add-item-row"><select value={menuId} onChange={e=>setMenuId(e.target.value)}><option value="">Select menu item…</option>{menu.map(item=><option key={item.id} value={item.id}>{item.name} — TZS {item.price_amount.toLocaleString()}</option>)}</select><div className="quantity-picker"><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><label>QTY<input type="number" min="1" max="999" value={quantity} onChange={e=>setQuantity(Math.min(999,Math.max(1,Number(e.target.value)||1)))}/></label><button onClick={()=>setQuantity(Math.min(999,quantity+1))}>+</button></div><button onClick={addItem} disabled={!menuId||busy}>{busy?"Adding…":`Add ${quantity}`}</button></div>{error&&<p className="form-error">⚠ {error}</p>}
    </section>
    <section className="content-card"><div className="card-heading"><div><p className="eyebrow">PAYMENTS</p><h2>Verified payment history</h2></div>{isAdmin&&remaining>0&&<button className="outline-button" onClick={simulate}>Simulate confirmation</button>}</div>
      <div className="payment-list">{payments.map(payment=><div key={payment.id}><span><b>TZS {payment.amount.toLocaleString()} · {payment.payment_method}</b><small>{payment.provider_reference||"Awaiting provider reference"}</small></span><span className={`status-chip ${payment.status==="PAID"?"paid":"pending"}`}>{payment.status==="PAID"?"✓ Verified":"◷ Pending"}</span></div>)}{!payments.length&&<div className="empty-inline">No payments yet. The customer can review the bill through the table QR.</div>}</div>
    </section>
    <section className="content-card totals-card"><div><span>Order total</span><b>TZS {total.toLocaleString()}</b></div><div><span>Paid and verified</span><b>TZS {paid.toLocaleString()}</b></div><div className="remaining-total"><span>REMAINING</span><strong>TZS {remaining.toLocaleString()}</strong></div>{sessionStatus==="SETTLED"&&remaining===0&&<><p className="form-success">✓ Payment is complete. The table will remain settled until staff closes it.</p><button className="staff-button" onClick={closeTable} disabled={busy}>{busy?"Closing…":"Close table"}</button></>}</section>
  </div>;
}